CREATE TABLE Address (
                         id bigint generated by default as identity (start with 1),
                         city varchar(30)  ,
                         street varchar(30)  ,
                         postal_code varchar(30) ,
                         home_number varchar(30)  ,
                         person_id int  ,
                         CONSTRAINT Address_pk PRIMARY KEY (id)
);


CREATE TABLE Person (
                        id bigint generated by default as identity (start with 1),
                        name varchar(30)  ,
                        last_name varchar(30) ,
                        age int ,
                        user_id int ,
                        CONSTRAINT Person_pk PRIMARY KEY (id)
);

CREATE TABLE User (
                        id bigint generated by default as identity (start with 1),
                        user_name varchar(30)  ,
                        password varchar(30)  ,
                        CONSTRAINT id PRIMARY KEY (id)
);
ALTER TABLE Address ADD CONSTRAINT Address_Person
    FOREIGN KEY (person_id)
        REFERENCES Person (id);


ALTER TABLE Person ADD CONSTRAINT Person_User
    FOREIGN KEY (user_id)
        REFERENCES User (id);
